Lee minju
Lee-Minju/java-ladder pull request #1
Opened 2024-01-23 14:36 UTC by Lee-Minju

2024-01-26 08:37 UTC, Cyma-s reviewed
안녕하세요 민주님 :) 오랜만입니다! 미션 하시느라 고생 많으셨어요 ㅎㅎ
전반적으로 코드가 훨씬 깔끔해졌고, 객체에게 책임을 분리해주시려고 노력하셨던 흔적들을 코드에서 발견할 수 있었습니다 😄
민주님의 코드에서 추가로 더 생각해볼만한 부분들이 있어 리뷰 남겼어요! 편하실 때 확인하시고 다시 리뷰 요청 주시면 감사하겠습니다 :) 물론 질문과 답글은 언제든 환영입니다! 첫 리뷰 파이팅이에요 🔥

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/controller/LadderController.java
> +  private Players makingPlayers() {
메서드는 접근 제한자를 처음부터 public 으로 열어두지 않고 private 으로 선언하면 리팩터링 하면서 발생하는 휴먼 에러를 줄일 수 있습니다 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/controller/LadderController.java
> +  OutputView outputView;
여기에는 private final 키워드를 사용하지 않으신 이유가 있을까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +    validatePlayers();
보통 값에 대한 검증을 수행하는 validate 메서드는 값을 필드에 할당하기 전에 실행되어야 합니다! 왜 그러는 것이 좋을 지 생각해보시고 생각해보신 내용을 댓글로 달아주세요 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +    isDuplicate();
조금 더 적합한 이름이 있을 것 같습니다 🧐 현재 클래스가 Players 임을 고려했을 때, 어떻게 짓는 것이 더 바람직할까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +    }
이 부분은 `hashcode` 와 `equals` 메서드를 사용하면 통해 좀 더 간결하게 줄일 수 있을 것 같아요! 
어떻게 수정할 수 있을지 고민해보시고 리팩터링 해주시면 되겠습니다 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/controller/LadderController.java
> +  OutputView outputView;
LadderController 가 InputView 와 OutputView 를 필드로 갖게 구현해주셨는데, 그렇게 구현해주신 이유가 있으신가요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/controller/LadderController.java
> +  public LadderController(InputView inputView, OutputView outputView) {
마찬가지로 생성자로 OutputView 와 InputView 를 입력 받도록 해주셨는데, 필드에 값을 대입하지 않으시고 생성자로 주입해주는 방식을 택하신 이유가 있을까요? 이 방법을 선택했을 때 어떤 이점이 있을까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/LadderDepth.java
> +  private final int depth;
원시 값인 depth 를 불변으로 포장해주셨네요! 👍
이런 불변 객체를 선언해주었을 때 장단점은 무엇이 있을까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +  }
해당 메서드를 따로 만들어주신 이유가 있으실까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/LadderDepth.java
> +  }
검증 좋습니다 👍🏻👍🏻👍🏻👍🏻

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Line.java
> +  }
random 이 객체 내부에 존재하게 되면서 Line 을 테스트하기 어려울 것 같아요 🤔 어떻게 해결해 볼 수 있을까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Player.java
> +  private Name playerName;
현재 클래스의 이름이 `Player` 인데 필드 이름을 `playerName` 으로 지어주셨는데요! 이렇게 하면 이름에 `player` 라는 단어가 중복해서 들어가기 때문에 의미 중복이 발생합니다 😅 어차피 `player.name` 과 같은 식으로 사용되기 때문에 클래스의 이름이 필드 이름에 포함되지 않는 것이 가독성이 더 좋습니다 👍🏻

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +public class Players {
`List<Player>` 를 갖는 `Players` 클래스를 정의해주셨네요 👍🏻👍🏻
이런 클래스를 만드시게 된 이유가 궁금합니다 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +    validatePlayers();
`numberOfPlayers` 라는 필드가 추가된 이유가 궁금합니다!!

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +  }
필드 값에 접근을 할 때는 getter 의 이름 컨벤션을 따르는 것이 좋습니다 ☺️

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Position.java
> +  private int position;
`Position` 은 불변 객체가 아니게 설정해주셨네요! 이렇게 구현하신 이유가 있으실까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Position.java
> +  private int position;
이건 취향이긴 하지만 값 객체의 필드 이름은 `value` 라고 하기도 한답니다 ㅎㅎ
해당 리뷰는 좋다고 생각하시면 적용하시면 되고, 민주님의 관점에 따라 적용하지 않으셔도 좋습니다!

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Player.java
> +  public String getPlayerNameString() {
메서드와 필드에는 객체의 '타입' 이 명시되지 않는 것이 좋습니다! 만약 추후 데이터를 저장하는 타입이 달라지게 된다면, 메서드의 이름도 달라져야 하기 때문에 유지보수에 어려움이 있어요 🥲

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/view/OutputView.java
> +  public String makingBlank(int lengthOfName) {
메서드 이름은 동사로 시작하도록 작성해주세요 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/view/OutputView.java
> +  private final int MAKE_BLANK_FIVE = 6;
상수를 포함한 변수의 이름은 명사여야 합니다!

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/view/OutputView.java
> +      }
다음과 같이 작성해볼 수도 있겠네요 :)
```suggestion
      if (lineValue.get(j)) {
        ladderParts += "-----|";
        continue;
      }
      ladderParts += "     |";
```

2024-01-26 08:37 UTC, Cyma-s commented on src/test/java/DepthTest.java
> +    int result = ladderDepth.getDepth();
getter 에 대해 테스트를 만들어주셨는데, 테스트를 만드시게 된 계기가 궁금합니다 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/test/java/LineTest.java
> +  void 플레이어_수에_맞는_라인_생성() {
테스트의 이름이 일관적이면 더욱 좋을 것 같습니다! 명사로 끝나거나, 아니면 동사로 끝마치거나 둘 중의 하나로 통일해주세요!

2024-01-26 08:37 UTC, Cyma-s commented on src/test/java/LineTest.java
> +    });
`Line` 내부에서는 현재 `Random` 이 사용되고 있는데요, 정말로 해당 테스트가 무작위 값으로 만들어진 `Line` 을 모두 테스트할 수 있을까요? 어쩌면 100만번째 테스트에서는 실패할 수도 있지 않을까요?
`Random` 이 객체 내부에 있게 되면, 우리가 작성한 테스트가 완벽하게 성공하는 테스트인지 알 수 없습니다. 그렇다면 객체 외부에 `Random` 을 둘 수는 없을까요? 어떤 구조로 변경하면 좋을지 고민해보시면 좋을 것 같습니다 :)

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Position.java
> +  }
position 의 값으로 음수가 들어온다면 어떻게 될까요?

2024-01-26 08:37 UTC, Cyma-s commented on src/test/java/LadderTest.java
> +    });
테스트 이름만 보면 예외가 발생하는 테스트인 것 같은데, 실제로는 정상 동작 테스트를 하고 있네요 🤔

2024-01-26 08:37 UTC, Cyma-s commented on src/test/java/PlayersTest.java
> +    Player testPlayer1 = new Player(new Name("pobi"), new Position(0));
다음과 같은 코드와는 어떤 차이점이 있을까요? 민주님은 어떤 코드가 더 좋다고 생각하시는지 궁금합니다 :)

```suggestion
    Player testPlayer1 = new Player("pobi", 0);
```

제 의견이 무조건 정답은 아니니 편하게 말씀해주세요 😄

2024-01-26 08:37 UTC, Cyma-s commented on src/main/java/domain/Position.java
> +  }
`moveLeft` 와는 다르게 여기에는 제약 조건이 없네요! 오른쪽으로는 계속해서 움직일 수 있을까요?

2024-02-02 07:35 UTC, Lee-Minju commented on src/main/java/controller/LadderController.java
> +  private Players makingPlayers() {
코드 작성 연습을 많이 하지 않을 때 무심코 모두 public 으로 선언하던 습관이 남아 있는것 같아요. 😅

코드의 안정성이나 보안 측면에서 private를 사용하는 것이 필요하다는 것과 클래스 내부에서 사용된다면 private로 충분하다는 점을 깨달은 것이 얼마 되지 않아서 그런 것 같기도 합니다.
필요할 때만  public으로 변경하기로 습관을 들이려고 이번에 참고해서 코드를 작성했습니다.

2024-02-02 07:49 UTC, Lee-Minju commented on src/main/java/controller/LadderController.java
> +  OutputView outputView;
필드 변수 중에 앞으로 변경되지 않을 것에 final 을 붙이려 생각하고 코드를 작성했었는데, 사용하는 것을 빼먹었네요.

필드로 갖게 구현한 것은 컨트롤러의 메소드별로 View의 인스턴스를 생성하는 것보다는 하나의 InputView 와 OutputView 객체를 필드에 생성한 채 컨트롤러가 동작하는게 간결하다고 생각해서 이 방식으로 코드를 작성했습니다.

이번 리뷰를 참고해서 코드를 작성한 것을 다시 살펴보면서 아직 객체지향에 익숙하지 않다는 것을 느낄 수 있는 점이 몇몇 있었는데, 밑에서 언급해주신 생성자 주입 방식 같이 인스턴스 생성, 의존성 관계같은 내용을 생각하지 않고 있구나 라고 느꼈어요. 💦 앞으로 찾아 공부도 하고 신경 쓸 부분을 발견한 것 같습니다. 😄

2024-02-02 07:59 UTC, Lee-Minju commented on src/main/java/domain/Players.java
> +    validatePlayers();
단순하게 오류나는 부분을 고치려고 신경안쓰고 할당과 검증의 순서를 바꿨던 부분이에요.

할당을 먼저 해두면 값이 이미 메모리를 채우고 있고 필요하다면 비워주어야 하기 때문에, validate가 문제 없을 때 필드를 할당해주는 것이 옳다고 생각합니다. 검증 -> 실적용이 일반적인 작동 순서에도 맞다고 느꼈습니다.

이를 참고해서 기존 Ladder 클래스에서 Ladder를 생성하는 순서를
[ 자신의 필드 lines 에 값을 add() -> 검증하고 문제가 있다면 자신의 lines 를 clear() 하고 재시작 ] 에서
[ 후보 lines를 생성 -> 이를 검증하고 문제가 있다면 재시작, 문제가 없다면 필드에 적용] 
으로 구조를 수정했습니다.

2024-02-02 08:02 UTC, Lee-Minju commented on src/main/java/domain/Players.java
> +    isDuplicate();
Players 클래스니까, Players의 관점이라면 Player의 이름이 중복되는지 확인하는 과정이므로 이름을 hasDuplicatedName() 으로 수정했습니다.

2024-02-02 08:10 UTC, Lee-Minju commented on src/main/java/domain/Players.java
> +    }
기존에는 중복을 확인할 때 HashSet을 사용하고 길이를 비교해 확인하는 방식만 알고 있었어요.

이번에 hashCode() 의 사용 형태에 대해서 찾아보게 됬는데, HashSet에 문자열이 아니라 객체 단위로 들어가면 정확하게 중복 확인을 할 수 없다는 것도 처음 알게 됬습니다. 객체 단위로 정확한 중복 확인을 하기 위해서 사용자가 오버라이드해서 사용하는 방식을 처음 찾아보게 되었습니다. 나중에 필요할 때에 사용할 수 있을 것 같아 유용하다고 느꼈습니다. 

hashCode를 사용하면 HashSet에 이름의 문자열만 빼서 넣는게 아니라 Player 자체를 넣게 코드를 작성할 수 있으니까 코드가 'this.getPlayerByIndex(i).getPlayerNameString()' 처럼  읽기 어려운 부분이 간결하게 바뀔 수 있다고 느꼈습니다.

2024-02-02 08:16 UTC, LEE-MINJU1107 commented on src/main/java/controller/LadderController.java
> +  public LadderController(InputView inputView, OutputView outputView) {
특별하게 계획하고 작성한 것이 아니라 의식의 흐름(?) 대로 작성한 부분이었습니다. 
이번에 코드를 작성할 때는 TDD 방법론과 MVC 모델구현에 집중했었는데요, 이 점에 집중하다 보니까 본 코드를 의식으 흐름대로 작성한 점이 있는 것 같아요. 😓 

리뷰를 읽어보면서 의존성 주입. 생성자 주입이나 필드 주입같은 개념도 찾아 읽어볼 수 있었습니다. 기존에는 알지 못하던 내용이라 앞으로 객체지향에 공부할게 많구나 라고 느꼈습니다. 👍 
다음에 코드를 작성 할 때는 인스턴스나 메소드 간의 의존성에 대해서도 생각하면서 코드를 작성해보자 라고 생각했습니다.

2024-02-02 08:23 UTC, Lee-Minju commented on src/main/java/domain/LadderDepth.java
> +  private final int depth;
요구사항에 원시값을 포장하라는 표현을 참고해서 작성해 보았습니다.

  '원시값 포장' 이라는 표현이 생소에 찾아보면서 작성했는데, 포장하고 내부의 필드를 불변 객체로 한다면 코드의 오류를 줄일 수 있고 보안(?) 측면에서 좋아지겠다 라고 생각했습니다. 

  Player가 그저 문자열로 name을 갖고 정수로 depth를 갖는다면 이에 대한 검증을 둘 다 Player 클래스에서 수행해야 하는데, 원시값이 포장된다면 각자의 클래스에서 검증하면 되니까 코드 구조를 더 간결하고 안정적이게 작성할 수 있다고 생각했습니다. 만약 수정이 필요 할 때에도 Player에 쪽에서 수정을 하려면 복잡해지는 것을 작은 클래스 내부에서 수정할 수 있을 것 같다고 생각했습니다.

2024-02-02 08:25 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
> +  }
TDD 방식으로 테스트를 먼저 작성하고 이를 통과하게 본 코드를 작성하는 과정에 집중하다 보니까, getter 메소드를 무분별하게 만들었던 것 같습니다.

리팩터링 과정에서 메소드를 정리해서 중복된 기능의 getter들을 줄이고 사용하지 않는 메소드를 삭제했습니다.

2024-02-02 09:01 UTC, Lee-Minju commented on src/main/java/domain/Players.java
> +public class Players {
먼저 요구사항을 읽으면서 사다리를 생성하는데에는 Player가 최소한 두명 이상은 되어야 한다고 판단했고, 사용자가 서로 중복된 이름을 입력하는 것을 잘못된 입력으로 판단해야 한다고 생각했습니다. Player의 수를 확인하거나 Player들의 이름을 서로 체크하려면 컨트롤러에 올라가기 전에 이를 검증하는 클래스가 필요하다고 생각해서 Players 클래스를 정의했습니다.

2024-02-02 09:20 UTC, Lee-Minju commented on src/main/java/domain/Players.java
> +    validatePlayers();
컨트롤러에서 사용자 수가 필요할 때 Players.getvalue.size() 로 사용하는 것이 읽기에 좋지 않다고 생각해서 필드로 두었습니다. 필드로 둘 때에 원시값 포장을 하지 않는 것 같아서 고민했었는데 간결함이 있어야 할것 같아서 필드로 선언했습니다.

getter 메소드를 정리하면서 필드 변수로 두지 않고 필요한 값을 제공하는 메소드 만드는 쪽으로 리팩터링 했습니다 😄

2024-02-02 09:21 UTC, Lee-Minju commented on src/main/java/domain/Position.java
> +  private int position;
Position은 후에 사다리 게임의 결과를 진행하면서 값이 변할 거라고 생각해서 final을 사용하지 않았습니다!

2024-02-02 09:25 UTC, Lee-Minju commented on src/main/java/domain/Position.java
> +  private int position;
코드를 작성하면서도 Player 내부에 Name, Name 내부 값 문자열 name... 이런 명칭이 제가 느끼기에도 헷갈려서 이게 괜찮나? 했었던 부분입니다. 😅 

value쪽으로 사용하는 것이 읽기에도 더 편하게 느껴서 이를 반영했습니다.

2024-02-02 09:27 UTC, Lee-Minju commented on src/main/java/domain/Player.java
> +  public String getPlayerNameString() {
저번에도 지적해주셨던 내용인데 변수 이름 짓는데 고민하다 지어버린 이름입니다. 수정했습니다. 👍

2024-02-02 10:49 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +    validatePlayers();
매우 좋은 답변입니다 👍🏻👍🏻👍🏻

2024-02-03 11:19 UTC, Lee-Minju commented on src/main/java/view/OutputView.java
> +      }
라인 수를 줄일 수 있겠네요! 라인 수의 제한이 있을 때라면 더 효과적일 것 같아서 수정했습니다.

2024-02-03 11:21 UTC, Lee-Minju commented on src/test/java/DepthTest.java
> +    int result = ladderDepth.getDepth();
이번에는 구현할 기능을 정리해서 실패하는 테스트를 먼저 작성하고, 다음으로 이를 해결하는 식으로 코드를 작성하는데 집중했습니다. 이 과정 중에 작성한 테스트입니다!

2024-02-03 12:01 UTC, Lee-Minju commented on src/test/java/LineTest.java
> +    });
`Random` 이 안에 있다보니 기존에는 앞 칸에 가로줄이 없을때만 랜덤으로 가로줄의 여부를 결정하게 하고, 가로줄이 있다면 빈칸으로 두게 라인을 생성하도록 구현했었습니다. 
동작에는 문제가 없었으나, `Line` 이 랜덤으로 생성되니까, 예외을 발생시키는 라인을 특정하기 어려워 직접적인 기능 테스트를 작성할 수 없어 우회적인 방식으로 테스트를 작성했었습니다.

직접적인 기능 테스트가 가능하도록 바꾸기 위해서, `NumberGenerator`  인터페이스를 만들고 `Line` 내부에는 `generateNumber()` 만을 작성해 두었습니다. 
여기에 맞춰 각 상황에 맞게 [ 랜덤하게 숫자를 생성 // 가로줄이 생기게 숫자를 생성 // 빈 칸이 되게 숫자를 생성 ] 하는 숫자 생성 클래스를 만들었습니다.
이렇게 구성하면서, 특정 라인이 필요할 때 맞춰서 라인을 생성할 수 있게 되었고 이를 테스트할 때에는 검증기능의 메소드를 테스트하게 수정했습니다.

2024-02-03 12:05 UTC, Lee-Minju commented on src/test/java/LadderTest.java
> +    });
`Ladder` 안에서 `Line` 의 가로줄 형태가 랜덤하게 생성되다 보니까 끊겨 있는 사다리를 의도해서 생성 할 수 없어 우회적으로 오류가 나지 않으면 된다 의 느낌으로 작성했던 테스트입니다.

Random을 외부로 배치하고 의도에 맞게 `Line`의 가로줄을 만들 수 있게, 즉 끊어진 사다리를 의도적으로 생성 할 수 있게 코드를 수정했습니다. 또한 직접적인 기능 테스트를 위해서 검증 기능의 메소드를 테스트하게 작성했습니다.

2024-02-03 12:27 UTC, Lee-Minju commented on src/test/java/PlayersTest.java
> +    Player testPlayer1 = new Player(new Name("pobi"), new Position(0));
`Name` 클래스와 `Postion` 클래스를 먼저 TDD 에 맞춰서 작성하고 그 다음으로 `Player` 클래스를 작성했었는데 ,  '자료형이 Name 이니까 생성자에서는 Name으로 받아야 겠지'  같은 마음으로 작성했던 부분입니다. 제안해주신 방식으로 작성하면 객체를 선언할 때 더 간결해져 읽기가 쉬워지므로 좋다고 느꼈습니다. 이에 Player 생성자 부분을 수정했습니다.

리뷰를 참고하면서 아직 객체지향에 익숙하지 않은점이 있다고 느꼈습니다. 익숙하지 않다보니 어떤것이 어떻게까지 표현이 가능하구나 같은 유연함이 부족한것 같습니다 ㅎㅎ

2024-02-03 12:33 UTC, Lee-Minju commented on src/main/java/domain/Position.java
> +  }
`Position` 클래스에 검증과정을 구현하지 않은 이유는 컨트롤러에서 사용자의 순서대로 넣어둔 리스트의 인덱스를 따라서 포지션을 배정하기에, 0 이상의 값이 들어와 문제가 없을 거라 생각했습니다.

2024-02-03 12:38 UTC, Lee-Minju commented on src/main/java/domain/Position.java
> +  }
맨 오른쪽에서 이동을 하려 할 때의 대응을 작성하려 했으나 사용자 수를 받아와야 해서 복잡한 구조가 되겠다고 생각이 들었습니다. 
그래서 `Position` 클래스 에서는 이동을 수행하고, 후에 게임 결과를 출력하는 메서드를  컨트롤러에서 구현 할 때 맨 왼쪽과 맨 오른쪽의 경우의 포지션 이동방식을 구현하자고 생각하게 되었습니다.

Position 클래스는 사다리를 출력하는 단계에서는 사용되지 않기에, 전체적인 형태만 구성해 둔 느낌이 있습니다. 😅 
추후 게임을 진행하고 결과를 출력하는 과정을 구현 할 때에 수정이 필요할 것 같습니다.

2024-02-03 12:55 UTC, LEE-MINJU1107 commented
안녕하세요 은솔님! 다시한번 리뷰 감사드립니다. 😸 
세심하게 리뷰해주셨던 내용이 많아서 하나하나 읽어보고 생각하느라 시간이 좀 걸렸던 것 같네요. 
오래 기다리시게 해 죄송합니다. 🙇
이번 리팩터링 과정에서는 생소 했던 것들을 찾아보는 경험이 많았던 것 같습니다. 인터페이스나 오버라이딩에 대해서도 찾아볼 수 있었습니다. 시간 여유 있으실 때 리뷰를 부탁드립니다. 
공부할 것들을 매번 잘 집어주시는 느낌이라 항상 도움이 많이 되고 있습니다!! 감사합니다. 😄

2024-02-03 23:52 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +    }
맞아요 👍🏻 `hashcode`, `equals` 는 객체 단위로 동등성을 비교할 때 많이 사용되니 알아두시면 좋습니다 ㅎㅎ
이 부분에 대해 좀 더 알아보고 싶으시다면 동일성과 동등성이라는 키워드로 검색해서 공부해보세요!

2024-02-03 23:54 UTC, Cyma-s commented on src/main/java/domain/LadderDepth.java
> +  private final int depth;
오!! 너무 좋은 답변입니다. 검증에 대한 책임을 값 객체에게 전달해줄 수 있어 많이 사용되는 패턴이에요 😄
앞으로는 어디까지 포장해야 하고, 어디까지 포장하지 않아도 되는지 고민이 되실텐데, 민주님이 생각하시는 기준을 잘 세워두시는 것이 좋습니다!

2024-02-03 23:56 UTC, Cyma-s commented on src/main/java/domain/Players.java
> +public class Players {
아주 좋은 판단입니다 👍🏻👍🏻👍🏻👍🏻

2024-02-03 23:57 UTC, Cyma-s commented on src/test/java/DepthTest.java
> +    int result = ladderDepth.getDepth();
간단한 getter 의 경우에는 테스트를 만들지 않아도 괜찮습니다! 민주님께서 '이 부분의 테스트는 있어야 내가 안심하고 기능을 만들 수 있겠는데?' 라고 생각되는 경우에 테스트를 만들어보는 것이 좋습니다 👍🏻

2024-02-03 23:58 UTC, Cyma-s commented on src/test/java/LineTest.java
> +    });
오오 ㅋㅋㅋ `NumberGenerator` 인터페이스를 만들어서 랜덤성을 분리해주셨군요 👍🏻 매우 좋은 접근입니다 :)

2024-02-04 00:02 UTC, Cyma-s commented on src/main/java/domain/Position.java
> +  }
이런 경우에는 다른 개발자가 내가 만든 객체를 사용하게 되었을 때를 생각해보면 좋습니다! 
현재는 입력이 콘솔에서만 주어지지만, 만약 해당 객체 생성을 다른 개발자가 다른 기능 개발을 위해 사용하게 된다면 여기에 명시되어 있지 않은 validation 에 대한 정보는 알 수 없겠죠?
그렇지만 이런 생각으로 validation 을 추가하는 것도 너무 많아지면 좋지 않은데요, 적당한 선에서 validation 을 하는 기준은 민주님께서 세워주시면 됩니다 :)

2024-02-04 00:43 UTC, Cyma-s requested changes
안녕하세요 민주님! 이번에 리뷰 반영해주신 내용들이 깊이가 있어서 많이 고생하셨겠다는 생각이 들었어요. 특히 인터페이스로 랜덤성을 분리하기 위해 전략패턴을 사용하신 모습이 인상깊었습니다 👍🏻👍🏻👍🏻👍🏻 너무 잘하고 계세요!
이번에는 분리해주신 `NumberGenerator` 에 대해 조금 더 생각해보실 수 있는 리뷰를 남겼어요. 제가 생각하기에 조금은 어렵게 느껴지실 수 있는 내용이라고 생각해서, 만약 너무 안 떠오르거나 도저히 모르겠다! 싶은 내용들은 댓글로 질문 주세요!
매번 리뷰 때마다 코드가 많이 깔끔해지고 있는 것 같아요 😄 이번 리뷰도 파이팅입니다 💪

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +      NumberGenerator numberGenerator = new RandomNumberGenerator();
`NumberGenerator` 를 makeLadder 에서 할당해주고 있네요!
해당 `NumberGenerator` 에 의해 사다리 생성 방법이 결정된다면, `NumberGenerator` 를 필드로 바꿔도 괜찮지 않을까요?
만약 사다리마다 다른 `NumberGenerator` 를 사용하고 싶다면 여기서 어떻게 구조를 변경하면 좋을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +  public void validateLadder(List<Line> candidateLines, int numberOfPlayers) {
`validateLadder` 의 접근제한자가 `public` 으로 바뀌게 된 이유가 있을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +  private Boolean isLadderSafe(List<Line> candidateLines, int lineIndex) {
여기에서 `Boolean` 을 리턴하게 되면 true, false 값이 `Boolean` 으로 wrapping 이 되는데요, boxing, unboxing 에 대해 알아보시고 댓글로 남겨주시겠어요?

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
>    }
`Ladder` 클래스에서 `Line` 들이 같은 줄에서 평행한지 확인하고 있네요. 이것의 검증은 어떤 클래스의 책임일까요? `List<Line>` 의 책임이라고 볼 수도 있지 않을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Line.java
> +  private Boolean makePoint(int number) {
`Boolean` 을 포장할 수는 없을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Line.java
> +      validateLine(candidatePoints, numberOfPlayers);
`makePoints` 를 하고 `validateLine` 을 했을 때, 랜덤으로 제대로 생성되지 않는다면 예외가 발생하고 게임이 종료될 것 같네요. 사용자의 잘못이 아니라 게임 내부 과정에서 예외가 발생하게 되는 경우는 프로그램에서 예외를 잘 처리해서 잘 작동되도록 해야해요. 지금 같은 경우에는 사용자가 혼란을 느낄 것 같은데, Line 이 처음부터 잘 생성되게 하는 방법은 없을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Player.java
> +  public String getPlayerNameValue() {
`getName` 으로 간결하게 표현할 수도 있을 것 같네요 :)

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Player.java
>    }
`equals`, `hashcode` 는 직접 만들면 처리해야 하는 예외가 많아져서, IDE 에서 제공하는 기능으로 `equals` 와 `hashcode` 를 재정의해주는 것이 좋습니다!!

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/domain/Players.java
>      }
한 번에 `Set` 에 모든 데이터를 삽입하고, `Set` 의 크기와 기존 `Player` 의 크기가 같은지 비교한다면 조금 더 간결하게 표현할 수 있을 것 같네요 🤔

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/tools/BlockedNumberGenerator.java
> +public class BlockedNumberGenerator implements NumberGenerator {
매우 훌륭한 구현입니다 👍🏻

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/tools/BlockedNumberGenerator.java
> +  private final int BLOCKED_NUMBER = 9;
해당 상수가 class 에 속하기 때문에, `private static final` 로 선언해주시는 것이 좋겠네요!

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/tools/NumberGenerator.java
> +
공백이 한 줄 더 있네요 😅

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/tools/RandomNumberGenerator.java
> +  private final Random random = new Random();
불변 필드로 선언한 부분 너무 좋군요 👍🏻👍🏻👍🏻

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/view/OutputView.java
> +  private final int BLANK_BASE = 6;
마찬가지로 class 에 속하는 '상수' 라고 생각하는 경우에는 `static final` 로 선언해주셔야 합니다 :)

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/view/OutputView.java
>    }
외부에서 입력받은 매개변수를 변경해서 리턴해주는 것은 추후 복잡한 코드를 짤 때 문제가 발생할 수 있어요. `drawLadder` 에서 모든 ladder 를 만들어서 리턴한다면 문제가 없을 것 같아요.

2024-02-04 00:43 UTC, Cyma-s commented on src/main/java/view/OutputView.java
>      String blank = "";
String 의 `repeat` 이라는 메서드를 사용해서 개선해볼 수도 있어요!

2024-02-04 00:43 UTC, Cyma-s commented on src/test/java/LadderTest.java
> +      testLadder.validateLadder(testLines, numberOfPlayers);
`validateLadder` 를 테스트하기 위해 해당 검증 메서드를 public 으로 만들어주셨는데요, 외부에서 `validateLadder` 를 쓰는 곳은 없는데 오직 테스트만을 위해 접근제어자를 변경하는 건 위험할 수 있어요. 해당 메서드를 남용할 수 있기 때문이죠.
`validateLadder` 를 public 으로 만들지 않으면서 어떻게 간접적으로 테스트를 할 수 있을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/test/java/LineTest.java
>      });
여기서는 `testLine` 에서 입력된 `NumberGenerator` 와 `validateLine` 에서 입력된 `testPoints` 를 테스트하기 위한  `NumberGenerator` 가 서로 다르네요! 테스트를 용이하게 하기 위해 이런 구조를 선택해주신 것 같습니다. 
마찬가지로 검증 메서드는 이 외부 테스트에서만 사용되고 있는데, public 으로 열어두게 되면 남용의 여지가 있어요. 마찬가지로 `validateLine` 을 public 으로 만들지 않고 `Line` 에 생성되는 Point 들을 검증하기 위해서는 어떻게 구조를 변경하는 것이 좋을까요?

2024-02-04 00:43 UTC, Cyma-s commented on src/test/java/PositionTest.java
`Position` 에 예외를 발생시키는 코드가 있기 때문에, 그 부분을 검증하는 테스트 코드가 필요할 것 같네요 :)

2024-02-09 13:03 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
> +  public void validateLadder(List<Line> candidateLines, int numberOfPlayers) {
`Ladder` 가 생성됬을 때 끊어져 있는지 검증하는 기능을 테스트하는 `LadderTest`에서 사용할 목적으로 `public`으로 변경했었습니다. 
밑에서 지적해주신 내용처럼, 보안측면에서 좋지 않은듯 해서 테스트의 내용을 수정해서 `validateLadder`를 private로 유지할 수 있게 했습니다.

2024-02-09 13:43 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
> +      NumberGenerator numberGenerator = new RandomNumberGenerator();
기존에 NumberGenerator를 어느 선에서 선언해서 적용할지 고민을 했었습니다. 기존에는 Line 단계에 넣어보려고 생각했었는데, 테스트를 위한 끊어진 사다리를 제대로 만들기 쉽지 않을 것 같아서 생각을 바꾸었습니다.

필드로 선언하게 되면 랜덤으로 사다리를 만드는 주문을 컨트롤러에서 하게 되므로, `RandomNumberGenerator`를 컨트롤러에 배치했습니다.  테스트를 할 때에는 다른 형태의 사다리를 개별적으로 주문할 수 있게 되서 필드로 선언한 것이 테스트에 더 용이하다고 느꼈습니다.

2024-02-09 14:17 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
>    }
일급 컬렉션을 사용하라는 요구사항에 더 알맞는 구현인것 같습니다. 이를 위해서 `Lines` 라는 클래스를 새롭게 생성했습니다. `Ladder` 내부의 `List<Line>` 을 포장하는 클래스로, 기존 검증내용과 생성내용을 수행하게 메소드를 이전했습니다.

2024-02-09 14:19 UTC, Lee-Minju commented on src/main/java/domain/Line.java
> +  private Boolean makePoint(int number) {
Name과 유사한 형태로 원시값을 포장할 수 있을것 같습니다. Point 클래스를 새로 생성해서 이곳에 가로줄의 여부를 저장하게 했습니다. 😄

2024-02-09 14:27 UTC, LEE-MINJU1107 commented on src/main/java/domain/Line.java
> +      validateLine(candidatePoints, numberOfPlayers);
지적해주신 내용처럼 기존에는 `Line`에서 가로줄이 겹쳐서 생성 되었다면 예외를 발생시키고 다시 만드는 과정을 문제가 없을 때까지 반복하게 했습니다. 만약 `Line`이 계속해서 올바르게 생성되지 않는다면 오버플로우를 발생시킬수 있다고 생각했습니다. 
이를 개선하기 위해서, `validateLine`이 제대로 생성됬는지 검사하고 예외를 발생시키는 것이 아니라, 문제가 있다면 문제를 수정하는 역할을 하게 변경했습니다.

2024-02-09 14:34 UTC, Lee-Minju commented on src/main/java/domain/Player.java
>    }
IDE에 자동생성기능이 있는지도 모르고있었네요 😅
자동생성기능을  `Player` 클래스에 사용했을때 제대로 동작이 되지 않았는데, `Name` 클래스에도 재정의를 해줘야 이름으로 `Player`를 구분할 수 있었습니다.

2024-02-09 14:36 UTC, Lee-Minju commented on src/main/java/domain/Players.java
>      }
`addAll()`을 생각못했었네요!!

2024-02-10 13:10 UTC, Lee-Minju commented on src/main/java/tools/BlockedNumberGenerator.java
> +  private final int BLOCKED_NUMBER = 9;
메소드나 변수를 다른 클래스에서 사용할 때 static을 선언한다고 알고있었습니다.
이번에 `final`과 `static final` 의 차이를 찾아보니까 `final`은 재할당을 불가능하게 하는 의미만 갖는 것을 알았습니다.
`static`을 선언하면 static 메모리에 한번 올라가고 선언하지 않으면 상수가 호출될 때 마다 인스턴스가 생성되어 stack 메모리에 올라가는 사실도 알 수 있었습니다. static 메모리가 stack 메모리와 별개로 존재함을 이번에 알게되었네요ㅎㅎ

진정한 '불변'의 의미를 담으려면 static 을 선언하는게 올바르다고 생각해보게 되었습니다. 메모리 절약측면에서도 static이 필요하다고 느꼈습니다. 👍

2024-02-10 13:15 UTC, Lee-Minju commented on src/main/java/view/OutputView.java
>    }
`drawLadder` 사다리의 한 층을 모두 리턴하게 수정했습니다!

2024-02-10 13:16 UTC, Lee-Minju commented on src/main/java/view/OutputView.java
>      String blank = "";
새로 알게 된 메소드입니다! 감사합니다. 😮

2024-02-10 13:30 UTC, Lee-Minju commented on src/test/java/LadderTest.java
> +      testLadder.validateLadder(testLines, numberOfPlayers);
테스트에서  가로줄이 모두 없는 `Lines`를 생성자로 생성하게 하고, 끊어진 `Lines`를 감지하고 예외를 발생시키는지 확인하게 했습니다.
이를 통해 validate 과정을 private 로 유지하면서 검증 기능을 테스트 할 수 있었습니다.

그리고 전체적인 형태인 `Lines`를 클래스로 분리시켜서 테스트 클래스의 이름을 `LinesTest`로 변경하였습니다.

2024-02-10 13:34 UTC, Lee-Minju commented on src/test/java/LineTest.java
>      });
`validateLine` 메소드가 직접 문제 사항을 고치도록 메소드를 수정했으므로, 제대로 고쳤는지를 확인하게 테스트를 구성해봤습니다.

테스트에서 생성자로 `testLine`을 생성하고, `testLine`의 안에 가로줄이 겹치는 부분이 있는지 확인해서 예외를 발생시키게 했습니다. 그래서 예외를 발생시키지 않으면 테스트를 통과하게 작성했습니다. 😄

2024-02-10 13:44 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
> +  private Boolean isLadderSafe(List<Line> candidateLines, int lineIndex) {
`Boolean` 과 `boolean`을 무분별하게 사용하고 있었습니다. `Integer`를 제외하고는 wrapper class 에 대해서 알고 있지 않았네요. 😓 

기본 타입(Primitive type) 의 값을 객체(wrapper class 의 인스턴스) 로 만드는 것을 boxing이라고 한다고 알게되었습니다.

자동으로 박싱&언박싱을 해주는 기능 때문에 모르고 무분별하게 사용하던 내용을 이제는 개념을 알고 사용할 수 있게 되었습니다.  그리고, 박싱을 포함한 형 변환은 결국에 성능에 영향을 끼치므로, 자제하는 것이 필요하다고 생각해 볼 수 있었습니다.

2024-02-11 08:31 UTC, Lee-Minju commented
다시 한번 리뷰 감사합니다! :)
리뷰를 참고하면서 이번에도 새로운 지식들을 찾아 볼 수 있었습니다.
수정을 할 수록 코드를 작성할 때 생각하는 내용이 늘고 있는 것 같아서 뿌듯한 느낌이 드네요. 😄
시간이 여유 있으실 때에 리뷰 부탁 드립니다.
연휴 즐겁게 보내시고 새해 복 많이 받으세요!! 🙇

2024-02-11 08:32 UTC, Lee-Minju commented on src/test/java/PositionTest.java
테스트를 추가했습니다. 추가로 사다리 게임의 결과를 만드는 기능을 개발 할 때에, 더 테스트가 추가 되어야 할 것 같습니다.

2024-02-12 05:33 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +  private Boolean isLadderSafe(List<Line> candidateLines, int lineIndex) {
맞아요! 미미하긴 하지만 그래도 어느 정도 성능에 영향을 끼칠 수도 있으니 알아두는 것이 좋습니다 👍🏻

2024-02-12 05:33 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
>    }
일급 컬렉션을 사용해주셨군요 훌륭합니다 👍🏻👍🏻👍🏻👍🏻

2024-02-12 05:35 UTC, Cyma-s commented on src/main/java/domain/Player.java
>    }
잘 찾아내셨군요 👍🏻 값 객체는 항상 `equals`, `hashcode` 를 설정해주는 것이 좋습니다 :)

2024-02-12 05:37 UTC, Cyma-s commented on src/main/java/tools/BlockedNumberGenerator.java
> +  private final int BLOCKED_NUMBER = 9;
맞습니다 :) [구글 컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) 에서는 `static final` 로 선언된 변수만 상수라고 정의하고 있습니다! 시간 나실 때 읽어보시면 좋을 것 같아요.

2024-02-12 05:39 UTC, Cyma-s commented on src/test/java/LadderTest.java
> +      testLadder.validateLadder(testLines, numberOfPlayers);
클래스 분리 좋습니다 👍🏻

2024-02-12 06:44 UTC, Cyma-s approved these changes
안녕하세요, 민주님! 연휴 잘 보내셨나요 ㅎㅎ 연휴 기간 동안 리뷰 반영하시느라 수고 많으셨습니다 👍
이번에 남긴 리뷰들은 중복되는 리뷰도 있고, 단순 코드 수정이 많아 Approve 하게 되었습니다! 남긴 리뷰들은 2단계 진행하시면서 천천히 반영해주세요 ㅎㅎ!
사다리 미션 2단계에서 뵙겠습니다~

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/controller/LadderController.java
>      LadderDepth ladderDepth = makeLadderDepth(players.getNumberOfPlayers());
`LadderDepth` 는 `Ladder` 생성자 내부에서 만들어줘도 되지 않을까요? 민주님이 `LadderDepth` 를 외부에서 만들어주신 이유가 궁금해요!

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +  public Ladder(LadderDepth depth, int numberOfPlayers, NumberGenerator ladderSetting) {
보통 생성자의 매개변수는 필드의 이름과 동일하게 적습니다!

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
>    private LadderDepth depth;
`depth` 를 포장했을 때 어떤 이점이 있었나요?

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Ladder.java
> +      this.lines = candidateLines;
`this.lines` 할당은 try, catch 가 완료된 다음에 할당하면 좋을 것 같네요 :)

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/view/OutputView.java
> +    blank = blank.repeat(count);
```suggestion
    String blank = " ".repeat(count);
```

이렇게 표현할 수도 있어요!

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Point.java
> +  public void setValue(boolean value) {
setter 를 둠으로써 `Point` 는 불변 객체가 아니게 되었어요 🤔 
값 객체가 불변이 아니라면 어떤 문제가 발생할 수 있을까요?

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Players.java
>      Set<Player> duplicateChecker = new HashSet<>();
```suggestion
    Set<Player> duplicateChecker = new HashSet<>(players);
```

이렇게 쓸 수도 있습니다 :)

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Player.java
> +  public String getName() {
👍🏻👍🏻👍🏻

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Name.java
>    }
getter 와 `hashcode`, `equals` 의 순서는 일관적으로 해주시는 것이 좋습니다! getter 가 위로 가거나, `hashcode`, `equals` 가 위로 가거나 해서요.

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Line.java
> +  private List<Point> points = new ArrayList<>();
`points` 에 미리 값을 할당하지 않고, `validate` 가 완료되고 나서 할당하는 것이 좋지 않을까요?

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Line.java
> +  private void validateLine(List<Point> candidatePoints, int numberOfPlayers) {
이 메서드는 `Line` 을 검증하기 보다는 `candidatePoints` 를 룰에 맞게 수정하고 있는 것 같아요. 이런 책임에 맞게 메서드의 이름을 지어주시면 좋을 것 같습니다 :)
그리고 `candidatePoints` 를 룰에 맞게 수정하는 것까지 `makePoints` 의 책임처럼 보이네요 🤔

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Lines.java
> +  private List<Line> value;
여러 개의 `Line` 들이 모여 있는 `List` 를 저장하고 있기 때문에, 변수 이름을 복수형으로 지어주세요!

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Lines.java
> +  }
`getValue` 로 `List` 를 그대로 리턴하고 있는데요, 리턴 받은 리스트 요소를 수정하거나 삭제한다면 어떻게 될까요?

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Line.java
> +          .equals(true)) {
`getValue` 로 값을 꺼내서 확인하기 보다는, `Point` 에게 책임을 부여해보는 건 어떨까요?

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Line.java
>    public Boolean getPoint(int index) {
이 부분은 아직 리턴 타입이 wrapper class 로 되어 있는데, 이유가 있을까요?!

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Lines.java
> +    int numberOfLine = candidateLines.get(0).getLength();
`candidateLines.get(0).getLength()` 값이 `Line` 이 가지고 있는 Point 의 개수이기 때문에, 조금 더 적합한 네이밍이 있을 것 같아요 :)

2024-02-12 06:44 UTC, Cyma-s commented on src/main/java/domain/Lines.java
> +    return (candidateLines.get(linesIndex).getPoint(lineIndex));
`candidateLines.get(linesIndex)` 를 `hasHorizon` 내부에서 하기보다, `Line` 을 `hasHorizon` 의 매개변수로 받으면 각자의 책임이 더 깔끔하게 분리될 것 같네요 !

2024-02-16 15:04 UTC, merged

2024-02-22 08:39 UTC, Lee-Minju commented on src/main/java/controller/LadderController.java
>      LadderDepth ladderDepth = makeLadderDepth(players.getNumberOfPlayers());
저도  처음에는 `Ladder` 생성과정 안에서 `LadderDepth` 를 생성하는 방법을 구상 했었는데, `LadderDepth `는 생성과정에 입력을 받는 부분이 있다보니까 따로 구성하는것이 좋겠다고 느껴서 분리했습니다.
  그리고 `LadderDepth` 의 입력에 대한 예외처리의 오류문에는 format 형태를 적용해서, 따로 예외를 받는 부분을 만들었기에 분리한 부분도 있습니다 ㅎㅎ

2024-02-22 08:41 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
> +  public Ladder(LadderDepth depth, int numberOfPlayers, NumberGenerator ladderSetting) {
수정했습니다!

2024-02-22 08:47 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
>    private LadderDepth depth;
사용자에게 입력받은 `depth`가 너무 짧으면 사다리가 올바르지 않다고 생각해서 검증과정이 필요하다고 판단 했었는데, `depth` 를 포장 하면서 내부에 검증 과정을 넣을 수 있었던 것이 이점인것 같습니다.

2024-02-22 08:54 UTC, Lee-Minju commented on src/main/java/domain/Ladder.java
> +      this.lines = candidateLines;
구조를 수정했습니다. 수정하고 나서 메소드의 역할에 맞게 이름을 수정했습니다. :)

2024-02-22 09:08 UTC, Lee-Minju commented on src/main/java/domain/Point.java
> +  public void setValue(boolean value) {
다른 메소드에서 객체의 값을 변경할 수 있게 되면서, 객체의 값을 예상하기 어려워질것 같습니다. 이에 setter 의 사용에 신중해야 한다고 한번더 느꼈습니다.

2024-02-22 09:18 UTC, Lee-Minju commented on src/main/java/domain/Line.java
> +  private List<Point> points = new ArrayList<>();
`addAll` 을 사용하니까 `NullPointerException`이 발생해서 작성 해둔 부분 이었는데, 다른 방법이 있었네요! 감사합니다.

2024-02-22 09:34 UTC, Lee-Minju commented on src/main/java/domain/Line.java
> +  private void validateLine(List<Point> candidatePoints, int numberOfPlayers) {
검증의 의미에 '문제 없게 한다'는 의미까지 포함해서 생각하고 있었네요. 메소드의 이름을 수정했습니다. :)
거기에 더해서 리뷰해주신 내용처럼 `makePoints`에서 규칙에 맞게 수정하는 것이 좀더 간결한 과정이라고 느껴서 메소드를 `makePoints`의 내부에서 호출되게 수정했습니다.

2024-02-22 09:50 UTC, Lee-Minju commented on src/main/java/domain/Lines.java
> +  }
getter 는 데이터의 복사본을 전달하기에, setter를 사용하지 않으면 본 데이터에는 영향이 없다고 알고있습니다.

2024-02-22 10:06 UTC, Lee-Minju commented on src/main/java/domain/Line.java
>    public Boolean getPoint(int index) {
`LineTest` 에서 `equals`를 사용하는 부분이 있어 Boolean을 사용했었는데, 다시 살펴보니까 [ .equals(true) ] 같이 작성해도 되지않아도 되는 구문을 사용하고 있었습니다. 😓  이 부분을 수정하면서 boolean으로 변경했습니다!

2024-02-25 15:47 UTC, Cyma-s commented on src/main/java/controller/LadderController.java
>      LadderDepth ladderDepth = makeLadderDepth(players.getNumberOfPlayers());
생성 과정에 입력을 받는다는 부분을 `LadderDepth` 가 알아야 할까요? 사용자가 입력한다는 행위가 중요한 것이 아니라 단순히 `LadderDepth` 로는 숫자만 넘어오게 됩니다.
그리고 `LadderDepth` 는 도메인인데, 지금 구조에서는 입력의 방식이 변경되면 생성 코드의 위치가 함께 변경되는 문제도 있습니다.

예를 들어 현재는 콘솔로 유저에게 값을 입력받지만 프론트엔드 페이지가 있는 사다리 게임이라면 HTTP API 를 통해서 값을 전달받을 수도 있겠죠.